[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# 只烧录不复位 — 用 flash.bat 或手动复位启动
runner = ["probe-rs", "download", "--chip", "STM32H723ZG"]
[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = ["probe-rs", "download", "--chip", "STM32H723ZG"]

rustflags = [
    # "-C", "link-arg=-Tlink.x",
    # "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tdefmt.x",
]

[env]
# DEFMT_LOG = "info"
DEFMT_LOG = "trace"
